"""Add resource_id, region, risk_associated to assets

Revision ID: 18ac24600a1a
Revises: ffd63743d464
Create Date: 2026-08-21 16:37:50.552732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ac24600a1a'
down_revision = 'ffd63743d464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('risk_associated', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('risk_associated')
        batch_op.drop_column('region')
        batch_op.drop_column('resource_id')

    # ### end Alembic commands ###
