"""add organization details fields and department owners

Revision ID: a818d4651f64
Revises: ce07100eef94
Create Date: 2026-09-08 14:52:30.160495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a818d4651f64'
down_revision = 'ce07100eef94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'department', name='uq_org_department')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('legal_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('work_arrangement', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('geographic_scope', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('geographic_scope')
        batch_op.drop_column('industry')
        batch_op.drop_column('business_address')
        batch_op.drop_column('work_arrangement')
        batch_op.drop_column('company_url')
        batch_op.drop_column('legal_name')
        batch_op.drop_column('logo_path')

    op.drop_table('department_owners')
    # ### end Alembic commands ###
