"""Add AI review fields to evidence

Revision ID: d3590b67b0a8
Revises: 18ac24600a1a
Create Date: 2026-08-24 16:05:48.937114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3590b67b0a8'
down_revision = '18ac24600a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_suggested_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_rationale', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_reviewed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('ai_reviewed_at')
        batch_op.drop_column('ai_rationale')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('ai_suggested_status')

    # ### end Alembic commands ###
