"""add setup_tasks table

Revision ID: ed2b6eea0406
Revises: 2652ffed750f
Create Date: 2026-09-07 15:05:16.302155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2b6eea0406'
down_revision = '2652ffed750f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setup_tasks')
    # ### end Alembic commands ###
