"""Rebuild policies: statuses, approvers, comments, controls linkage

Revision ID: f154dfc324bd
Revises: d3590b67b0a8
Create Date: 2026-08-24 16:48:25.277118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f154dfc324bd'
down_revision = 'd3590b67b0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_approvers',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('policy_id', 'user_id')
    )
    op.create_table('policy_assignees',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('policy_id', 'user_id')
    )
    op.create_table('policy_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_controls',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('policy_id', 'control_id')
    )
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('requirement_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('entities', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('effort_estimate', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('recurrence')
        batch_op.drop_column('effort_estimate')
        batch_op.drop_column('entities')
        batch_op.drop_column('requirement_text')
        batch_op.drop_column('external_url')
        batch_op.drop_column('file_name')

    op.drop_table('policy_controls')
    op.drop_table('policy_comments')
    op.drop_table('policy_assignees')
    op.drop_table('policy_approvers')
    op.drop_table('policy_approvals')
    # ### end Alembic commands ###
