"""Add NDA acceptance table for Trust Center

Revision ID: ffd63743d464
Revises: 60737a6231a8
Create Date: 2026-08-20 14:47:36.781323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd63743d464'
down_revision = '60737a6231a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nda_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nda_acceptances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nda_acceptances_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nda_acceptances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nda_acceptances_email'))

    op.drop_table('nda_acceptances')
    # ### end Alembic commands ###
